// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace boites_de_dialogues
{
	public partial class SheetViewController : NSViewController
	{
		#region Private Variables
        private string _userName = "";
        private string _password = "";
        private NSViewController _presentor;
        #endregion

        #region Computed Properties
        public string UserName {
            get { return _userName; }
            set { _userName = value; }
        }

        public string Password {
            get { return _password;}
            set { _password = value;}
        }

        public NSViewController Presentor {
            get { return _presentor; }
            set { _presentor = value; }
        }
        #endregion

        #region Constructors
        public SheetViewController (IntPtr handle) : base (handle)
        {
        }
        #endregion

        #region Override Methods
        public override void ViewWillAppear ()
        {
            base.ViewWillAppear ();

            // Set initial values
            UsernameTxtFiled.StringValue = UserName;
            PasswordTxtField.StringValue = Password;

            // Wireup events
            UsernameTxtFiled.Changed += (sender, e) => {
                UserName = UsernameTxtFiled.StringValue;
            };
            PasswordTxtField.Changed += (sender, e) => {
                Password = PasswordTxtField.StringValue;
            };
        }
        #endregion

        #region Private Methods
        private void CloseSheet() {
            Presentor.DismissViewController (this);
        }
        #endregion

        #region Custom Actions
        partial void BtnOK(Foundation.NSObject sender) {
            RaiseSheetAccepted();
            CloseSheet();
        }

        partial void BtnCANCEL(Foundation.NSObject sender) {
            RaiseSheetCanceled();
            CloseSheet();
        }
        #endregion

        #region Events
        public EventHandler SheetAccepted;

        internal void RaiseSheetAccepted() {
            if (this.SheetAccepted != null)
                this.SheetAccepted (this, EventArgs.Empty);
        }

        public EventHandler SheetCanceled;

        internal void RaiseSheetCanceled() {
            if (this.SheetCanceled != null)
                this.SheetCanceled (this, EventArgs.Empty);
        }
        #endregion
        
	}
}
